# File to make manual modifications in the data.

cricketers = [
    [
        'Adam Gilchrist',
        'Jacques Kallis',
        'Kumar Sangakkara',
        'Muthiah Muralidaran',
        'Sachin Tendulkar',
        'Ricky Ponting',
        'Dale Steyn',
        'Shane Warne',
        'Glenn McGrath',
        'AB de Villiers'
    ],
    [
        'Rahul Dravid',
        'Shivnarine Chanderpaul',
        'Matthew Hayden',
        'Anil Kumble',
        'Michael Clarke',
        'Virender Sehwag',
        'James Anderson',
        'Younis Khan',
        'Brian Lara',
        'Shaun Pollock'
    ],
    [
        'Mark Boucher',
        'Mitchell Johnson',
        # 'Mohammad Yousuf',
        'Kevin Pietersen',
        'Hashim Amla',
        'Daniel Vettori',
        'Mahela Jayawardene',
        'Graeme Smith',
        'Alastair Cook',
        'Harbhajan Singh'
    ],
    [
        'VVS Laxman',
        'Brett Lee',
        'Andrew Flintoff',
        'Mike Hussey',
        'Makhaya Ntini',
        'Justin Langer',
        'Inzamam ul Haq',
        'Zaheer Khan',
        'Shoaib Akhtar',
        # 'Graeme Swann'
    ],
    [
        'Chaminda Vaas',
        # 'Damien Martyn',
        # 'Matt Prior',
        'Ian Bell',
        'David Warner',
        'Jason Gillespie',
        'Chris Gayle',
        'Stuart Broad',
        'Virat Kohli',
        # 'Andy Flower'
    ],
    [
        'Michael Vaughan',
        # 'Andrew Strauss',
        'Brendon McCullum',
        'Morne Morkel',
        # 'Brad Haddin',
        # 'Ryan Harris',
        # 'Thilan Samaraweera',
        'Kane Williamson',
        # 'Matthew Hoggard',
        # 'Graham Thorpe'
    ],
    [
        'MS Dhoni',
        'Rangana Herath',
        # 'Steve Harmison',
        # 'Gary Kirsten',
        'Danish Kaneria',
        # 'Jonathan Trott',
        'Stephen Fleming',
        # 'Stuart MacGill',
        'Herschelle Gibbs',
        'Steve Waugh'
    ]
]

cities = [
    "Mumbai",
    "Delhi",
    "Bangalore",
    "Hyderabad",
    "Ahmedabad",
    "Chennai",
    "Kolkata",
    "Surat",
    "Pune",
    "Jaipur",
    "Lucknow",
    "Kanpur",
    "Nagpur",
    "Indore",
    "Thane",
    "Bhopal",
    "Visakhapatnam",
    # "Pimpri-Chinchwad",
    "Patna",
    "Vadodara",
    "Ghaziabad",
    "Ludhiana",
    "Agra",
    "Nashik",
    "Faridabad",
    "Meerut",
    "Rajkot",
    # "Kalyan-Dombivli",
    # "Vasai-Virar",
    "Varanasi",
    "Srinagar",
    "Aurangabad",
    "Dhanbad",
    "Amritsar",
    # "Navi Mumbai",
    "Allahabad",
    "Howrah",
    "Ranchi",
    "Gwalior",
    "Jabalpur",
    "Coimbatore",
    "Vijayawada",
    "Jodhpur",
    "Madurai",
    "Raipur",
    "Kota",
    "Chandigarh",
    "Guwahati",
    "Solapur",
    "Hubli Dharwad",
    "Bareilly",
    "Mysore",
    # "Moradabad",
    "Gurgaon",
    "Aligarh",
    "Jalandhar",
    "Tiruchirappalli",
    "Bhubaneswar",
    # "Salem",
    # "Mira-Bhayandar",
    "Thiruvananthapuram",
    # "Bhiwandi",
    # "Saharanpur",
    "Gorakhpur",
    "Guntur",
    # "Amravati",
    "Bikaner",
    "Noida",
    "Jamshedpur",
    "Bhilai",
    "Warangal",
    "Cuttack",
    # "Firozabad",
    "Kochi",
    "Bhavnagar",
    "Dehradun",
    "Durgapur",
    "Asansol",
    # "Nanded",
    "Kolhapur",
    "Ajmer",
    "Gulbarga",
    # "Loni",
    "Ujjain",
    "Siliguri",
    # "Ulhasnagar",
    "Jhansi",
    # "Sangli-Miraj & Kupwad",
    "Jammu",
    "Nellore",
    "Mangalore",
    "Belgaum",
    "Jamnagar",
    # "Tirunelveli",
    # "Malegaon",
    "Gaya",
    # "Ambattur",
    "Jalgaon",
    "Udaipur",
    "Maheshtala"
]

states = [
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttarakhand",
    "Uttar Pradesh",
    "West Bengal"
]
